### ISSUE TITLE
Linear pattern - cannot select reference

### ISSUE THREAD

**Issue by jj-uk** [realthunder/FreeCAD#557] opened 2022-09-18 14:34 UTC
To reproduce:

Part design:
Create a body - create a sketch - XY plane.
Create a rectangle, close sketch and pad.

Select the end of the rectangle pad, sketch on face.
![image](https://user-images.githubusercontent.com/10943625/190912258-5ad5c691-79dc-422e-abf0-59bd9d47167e.png)

Bring in geometry, Add a rectangle to the side, pad.
![image](https://user-images.githubusercontent.com/10943625/190912360-ca2afde0-0cb9-4482-9750-12e6109c84d7.png)
![image](https://user-images.githubusercontent.com/10943625/190912387-2e2e09ec-6600-49c7-97ed-5dd8a5d5e558.png)

Select pad, linear pattern, select reference, select edge of 1st pad. Nothing happens. 
![image](https://user-images.githubusercontent.com/10943625/190912433-a9f572fe-f3dd-4c2d-8d21-63e8b25cbd74.png)

This works ok in freecad 0.20, but not in daily or stable.

**Comment by discip** [comment] 2022-10-05 15:37
@realthunder
That is absolutely true!

This prevented me from getting my job done today!

Thanks in advance

**Comment by hobbymachinist** [comment] 2024-07-23 10:00
@realthunder ran into the same issue today, is there any workaround for this ? seems to work fine in Freecad 0.21.2

**Comment by jbayless** [comment] 2024-07-24 22:55
@hobbymachinist I have written a very, very bodged workaround here on this duplicate of the issue: https://github.com/realthunder/FreeCAD/issues/710

**Comment by hobbymachinist** [comment] 2024-07-25 00:01
Yikes, that's a gnarly workaround. I'm going to switch back to using Freecad 0.21.2 for now.

**Closed as completed** 2024-08-28 13:04 UTC

**Comment by discip** [comment] 2024-08-28 13:43
@realthunder
# Great, thank you very much! 😃👍
