### ISSUE TITLE
[Problem] Can the configuration table support column direction parameters?

### ISSUE THREAD

**Issue by 3xxx** [realthunder/FreeCAD#998] opened 2024-04-29 23:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 2024.408.0.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 20240407stable)
Hash: 973e4821bcd19a5a1af9ae3e1d2ed961aad0a8ab
Python 3.11.8, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: Chinese/China (zh_CN)
Installed mods: 
  * A2plus 0.4.64
  * Assembly3 0.12.2
  * Assembly4 0.50.9
  * BillOfMaterials 0.0.7
[/code]
```

### Subproject(s) affected?

Spreadsheet

### Problem description

For example, if I have multiple sets of parameters, and I want to use the configuration table function to switch column data groups. At the moment, it seems to be switching by line. Because the amount of data exceeds a dozen, it is difficult to organize the data in rows, so you need to use the mouse to click and hold the scroll bar below to move left and right, and scrolling up and down with the scroll wheel can be convenient to view multiple data. Thank you very much.
![Snipaste_2024-03-23_13-29-45](https://github.com/realthunder/FreeCAD/assets/10678867/ada9dbe4-4936-4686-9411-57ec185e6968)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment] 2024-09-04 00:10
Duplicate of #1024

**Closed as completed by realthunder** 2024-09-04 00:10 UTC
