### ISSUE TITLE
Issue in Techdraw with Dimension

### ISSUE THREAD

**Issue by Neubo** [realthunder/FreeCAD#642] opened 2022-11-20 17:09 UTC
Hello,

I have an issue with Dimension in Techdraw.
Just make a rectangle (Draf) and create a Projection Group.
Add some dimensions.

Before leaving, I get : 

![image](https://user-images.githubusercontent.com/92023797/202915538-0825e119-7974-4a54-8678-981b98b34de7.png)

Right after opening the file, I get:

![image](https://user-images.githubusercontent.com/92023797/202915586-5d311a2f-688e-4a0f-b38c-4dbf5e8f44f2.png)

my version:
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.1112.26244 +5306 (Git)
Build type: Release
Branch: LinkDaily
Hash: c64e4a49244a1c0ce9fd6455d18aa919d0db9c80
Python version: 3.8.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.2
Locale: French/France (fr_FR)

Thnaks ! don't hesitate to ask if you need any other information.

**Comment by richwein3** [comment] 2022-11-24 14:05
It is a bug which happens under Windows, Ubuntu Linux, linux mint, and with appimage and snap versions.  This bug did not exist in Version 2022.704 .  I'm not sure which release started having this issue.

Also reported now by mwlandolsi at https://forum.freecadweb.org/viewtopic.php?f=44&t=73155

The problem is that the dimensions are stuck at xy (0,0), lower left corner of the drawing sheet.  This is easily shown if you click on the VIEW and assign its properties to x=0, y=0, which moves the VIEW to the lower left corner.  Then the set of dimensions line up.  As the view is moved in X,Y the dimensions position is not updated.

I would be interested in hearing from someone testing this and **saying it doesn't happen on their system**.  That might help understand and characterize the bug better.

**Closed as completed** 2022-11-27 02:25 UTC
