### ISSUE TITLE
FEM not working

### ISSUE THREAD

**Issue by tiket18** [realthunder/FreeCAD#67] opened 2020-11-20 21:37 UTC
OS: Arch Linux (GNOME/gnome-xorg)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.11.16.22739 +2766 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 6730ad3b3bd841c2745ec98bf953c523dea86913
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: Russian/Russia (ru_RU)

Refuses to create a grid. Judging by the report and processor load - creates. But it does not show, does not show.
![Снимок экрана от 2020-11-21 00-36-29](https://user-images.githubusercontent.com/18741088/99852296-c4fb7c00-2b91-11eb-90a2-93029e585e65.png)
[сидушка.FCStd.zip](https://github.com/realthunder/FreeCAD/files/5576219/FCStd.zip)

**Comment by davidosterberg** [comment] 2020-12-12 22:33
I have the same issue.

With LinkStage3 (2020-12-08 AppImage)
![FEM_FreeCAD_Linkstage3](https://user-images.githubusercontent.com/1278189/101996299-801abf00-3cd1-11eb-9db7-5e6035049d16.gif)
With standard FreeCAD 0.19. it works
![FEM_FreeCAD_standard](https://user-images.githubusercontent.com/1278189/101996303-91fc6200-3cd1-11eb-8c05-1e05b2284d6e.gif)

**LinkStage about info**
OS: Ubuntu 20.10 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.12.08.23076 +2912 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 1eba27283118bae43f5264d38caf7451b848f49a
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Vanilla FreeCAD about info**
OS: Ubuntu 20.10 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23058 (Git) AppImage
Build type: Release
Branch: master
Hash: 6e60870ebcb2df018adb7a1281c00dde87750f11
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

Example file: (Remove zip filename prefix)
[link_fem_bug.FCStd.zip](https://github.com/realthunder/FreeCAD/files/5683848/link_fem_bug.FCStd.zip)

**Comment by davidosterberg** [comment] 2020-12-12 22:41
@berndhahnebach do you know what might be causing this?

**Comment by realthunder** [comment] 2020-12-13 03:52
This is caused by missing installation of gmsh command line in my release. It's been fixed now. Will make a new release soon.

**Closed as completed** 2020-12-13 03:51 UTC
