### ISSUE TITLE
Toggling the visibility of padded object has no effect to its child sketch

### ISSUE THREAD

**Issue by jx2014** [realthunder/FreeCAD#155] opened 2021-07-01 06:49 UTC
steps to reproduce the issue:

1. create a new part
2. create a new body
3. create a new sketch
4. pad the sketch
5. <img width="457" alt="Capture3" src="https://user-images.githubusercontent.com/7607066/124077002-d34d2880-d9fb-11eb-84c1-cb91f00bcc72.PNG">
5. toggle the visibility of the part, everything disappears, this is expected.
6. toggle the visibility of the body, everything disappears, this is expected.
7. <img width="460" alt="Capture4" src="https://user-images.githubusercontent.com/7607066/124077006-d3e5bf00-d9fb-11eb-9ffc-60d33204d8ee.PNG">
7. toggle the visibility of the pad, the sketch remains visible, this is unexpected.
8. <img width="481" alt="Capture5" src="https://user-images.githubusercontent.com/7607066/124077008-d3e5bf00-d9fb-11eb-99b9-711c1c2240a6.PNG">
9. why is this a problem? sometimes it can create confusions when there are multiple padded objects, in which case one needs to manually toggle the visibility of each sketch. 
10. <img width="440" alt="Capture6" src="https://user-images.githubusercontent.com/7607066/124079213-b74a8680-d9fd-11eb-8303-52eb90a93fac.PNG">

> OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.614.24301 +3584 (Git)
Build type: Release
Branch: LinkStage3
Hash: d1e4d1c5abdedda669e54d1a41b5c08077f7e561
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

**Comment by Rabbit-sk** [comment] 2021-07-15 10:19
When you create a pad from a sketch, the sketch visibility is automatically turned off.
So if you turn off the visibility of the pad, the sketch is also not visible, because it was already not visible.

> toggle the visibility of the pad, the sketch remains visible, this is unexpected.

You can toggle the visibility of solid features (pads, pockets, ...), and their child non-solid features (sketches, ShapeBinders, ...), independently  and it is not a bug but a feature. 

Many times it is convenient to turn off the visibility of the solid shape in a body and turn on the visibility of its sketch. For example, when creating external geometry in a different sketch in the same body. Also for simple selection of particular edges when creating SubShapeBinder in another body, as well as in other cases.

**Comment by luzpaz** [comment] 2022-01-18 22:09
Closing ticket

**Closed as completed by luzpaz** 2022-01-18 22:09 UTC
