### ISSUE TITLE
Dual  monitor, preferences opens centered between monitors

### ISSUE THREAD

**Issue by snelweg** [realthunder/FreeCAD#116] opened 2021-03-08 18:33 UTC
A cosmetic issue, but sometime quite annoying nonetheless.

When on a dual monitor setup, FC on its own monitor, then opening the preferences dialog opens exactly in the middel between the monitors.
Would be nicer if it did open on the active FC monitor.
(the gray part in the video is the left monitor, the right monityor is where FC runs)

https://user-images.githubusercontent.com/1257901/110365235-134f6080-8045-11eb-87c3-8119c057650b.mp4

**Comment by dickshaydle** [comment] 2021-03-17 23:23
I also find this pretty annoying. Every time I open preferences I have to move it because it is half way outside the visible area because it is displayed on the smaller monitor.

What about saving the last window position?

**Comment by realthunder** [comment] 2021-03-18 02:27
Can you guys post more details? Your FreeCAD About information. Screen size of both of your monitors. Which one is the primary screen. I can't reproduce the problem. The preference window position is remembered and restored on open. And it always pop up on my primary screen regardless of where FreeCAD main window is.

**Comment by snelweg** [comment] 2021-03-18 10:28
oops
Main (primary) monitor (the one on the right) 1920x1080, left one 1360x768
On my setup the Preferences screen always opens up right between the two monitors, as if it centers on the total width of both monitors. I am using XFCE as window manager, maybe that causes problems? 
Even after restarting FC the same positioning.


> OS: Debian GNU/Linux 10 (buster) (XFCE/lightdm-xsession)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.311.24301 +3373 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 91ca94db328bf6126c4a01547b6aa2202d876ebc
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by wohltat** [comment] 2021-03-18 12:35
![2021-03-18_13-19-36_3046x1050](https://user-images.githubusercontent.com/4751351/111626066-daa24a80-87ed-11eb-9a62-3a276fdc5f81.png)

The black part on the top left is outside of the visible screen. The left screen is the primary monitor.

The preference window is always opened to the same position, no matter what i do. So far, i have not seen any modal window of which the position or size is saved/restored.

```
OS: Linux Mint 20.1 (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.311.24301 +3373 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 91ca94db328bf6126c4a01547b6aa2202d876ebc
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)
```

**Comment by snelweg** [comment] 2021-03-18 12:45
> The preference window is always opened to the same position, no matter what i do. So far, i have not seen any modal window of which the position or size is saved/restored.

But your screen looks different then mine. The dialog box opens on your primary  monitor centered horizontally. On my setup it opens centered between monitors. Maybe there is indeed same saved setting somewhere that 'remembers' old values.

**Update**: I can confirm my suspicions. I threw away the .FreeCAD directory and after FC was started the preference dialog opened neatly centered in the middle of the FC screen.
So there is some forgotten setting in one of the .FreeCAD files that makes our screen layout act strange.

**Comment by realthunder** [comment] 2021-03-18 13:11
That's strange. Do you still keep the old .FreeCAD directory? If so please post here your link.user.cfg file inside.

**Comment by snelweg** [comment] 2021-03-18 14:38
> That's strange. Do you still keep the old .FreeCAD directory? If so please post here your link.user.cfg file inside.

Yes I kept it. Switching back to the saved .FreeCAD directory same problem again.

[link.user.cfg.txt](https://github.com/realthunder/FreeCAD/files/6164945/link.user.cfg.txt)

**Comment by wohltat** [comment] 2021-03-18 17:43
There is actually a place where the position and size is stored (on "OK" not on "Apply").
_link.user.cfg:_
`<FCText Name="PreferenceGeometry">683 0 683 708</FCText>`

It is saved correctly, but on restoring there is something going wrong:
- The window is pulled to the first monitor even though i placed it on the second monitor before. 
- y position seems to be always set to "0" (which causes it to be outside visible area on my setup)
- The x/y size, x-position is restored correctly if the window stays on the first monitor
- if placed on the second monitor, the x/y size is reduced so it fits on the first monitor

**Comment by realthunder** [comment] 2021-03-18 22:03
The y position is not restored on Linux, because of some [peculiarity](https://doc.qt.io/qt-5/application-windows.html#x11-peculiarities) in Linux desktop environment. Can you try move the preference dialog a little bit, and then close it. It should save a non-zero value for y. Nevertheless, the saved y value is ignored during restore.

So the problem is mainly that Qt always show pop up window on the primary monitor, and if it has a lower resolution than the secondary monitor and the FreeCAD main window is in the secondary monitor, things get a little weird.

**Comment by wohltat** [comment] 2021-03-18 22:44
> So the problem is mainly that Qt always show pop up window on the primary monitor, and if it has a lower resolution than the secondary monitor and the FreeCAD main window is in the secondary monitor, things get a little weird.

Looks **line 439** is why only one monitor is considered. I would guess that "desktop()" uses the entire virtual desktop, that you can see in the screenshot of my previous post. This doesn't seem like a general Qt limitation to me, since the window is moved in virtual desktop coordinates (window is outside the first monitor). 
https://github.com/realthunder/FreeCAD/blob/acc8717c2b634e573ee8dfdc896372e970a2a310/src/Gui/DlgPreferencesImp.cpp#L438-L442

-------------

> The y position is not restored on Linux, because of some peculiarity in Linux desktop environment. Can you try move the preference dialog a little bit, and then close it. It should save a non-zero value for y. Nevertheless, the saved y value is ignored during restore.

As i said previously. The saving of the values works flawlessly. It's just the restoring of the values.
I can't see what the linked "peculiarities" have to do with this. As i read it, it only talks about why the size of the window is not predictable. Furthermore, why should it be different then the x-axis?
I can't understand what __line 477__ is good for. I'm pretty sure it is causing the problem i've seen.

https://github.com/realthunder/FreeCAD/blob/acc8717c2b634e573ee8dfdc896372e970a2a310/src/Gui/DlgPreferencesImp.cpp#L472-L479

**Comment by realthunder** [comment] 2021-03-18 23:18
`desktop()` code is only used in Qt4. Qt5 code uses the primary screen geometry, and it is only used to limited preference widget position. In all cases, the widget shouldn't be moved outside of the desktop.

The problem with X window is about the window decoration, i.e. the window border, title bar and stuff. Qt says it has trouble finding out the size of them. The net effect, at least when I tried on Ubuntu Gnome is that if I restore the Y value, the preference dialog will noticeably moving downward a bit each time you open it. So I decided to only restore X value and use the current Y. But then, X Window is asynchronous, by the time the move command reaches the server, something might have already happened. And that something may also be the reason why your dialog moved outside of your screen. I guess using a timer to delay the restore may be a solution. Not sure though.

**Comment by wohltat** [comment] 2021-03-19 00:13
>  In all cases, the widget shouldn't be moved outside of the desktop. ...

I agree. But it obviously is moved outside. I think using only the primary monitor geometry is not sufficient. Using `desktop()` should still work but since it is deprecated, some other solution would be preferable. For example maybe the following
https://doc.qt.io/qt-5/qscreen.html#availableVirtualGeometry-prop


> The problem with X window is about the window decoration ...

To get the displacement offset, one could try to perform a "save-restore-cycle". This means set coordinates, get coordinates and store the difference.

**Comment by wohltat** [comment] 2021-03-20 13:40
Much better now. But there are still some problems.
On the first monitor the window is squished in y-direction and on the second in x-direction.
Furthermore the window is force to be on the same monitor as the main window.

Personally i would prefer to simply be able to put it anywhere and it being restored that way without repositioning/resizing.
Just removing the constraints does the trick, since Qt somehow already cares for the window not being outside of the screen.

```c++
void DlgPreferencesImp::restoreGeometry()
{
    if (geometryRestored)
        return;
    geometryRestored = true;

    std::string geometry = App::GetApplication().GetParameterGroupByPath(
            "User parameter:BaseApp/Preferences/General")->GetASCII(
                "PreferenceGeometry", "");
    std::istringstream iss(geometry);
    int x,y,w,h;
    if (iss >> x >> y >> w >> h) {
        this->move(x, y);
        savedPos = QPoint(x, y);
        QMetaObject::invokeMethod(this, "resizeWindow",
                Qt::QueuedConnection,
                QGenericReturnArgument(),
                Q_ARG(int, w),
                Q_ARG(int, h));
    }
}
```

I tested it and it works fine on my system (Ubuntu 20.04, XFCE). But i don't how know this behaves on windows.

**Comment by wohltat** [comment] 2021-03-23 12:52
Just tested your commit and it works great in every possible constellation of the windows.

**Comment by wohltat** [comment] 2021-08-23 09:21
@snelweg i guess this issue can be closed

**Closed as completed** 2021-08-23 10:06 UTC
