### ISSUE TITLE
Selecting external geometry from a binder *sometimes* maps incorrectly

### ISSUE THREAD

**Issue by kevenwyld** [realthunder/FreeCAD#416] opened 2022-05-18 04:28 UTC
See the below video.  When I reference external geometry from the binder I have created in this file arcs seem to be referenced incorrectly while straight lines are fine.

https://user-images.githubusercontent.com/11936535/168956421-e87f6e08-61be-44e7-82ec-0909e24533ff.mp4

Here are the two files you will need to reproduce the problem.  Open `encoder_mounting_bracket_take2.FCStd` which will reference `encoder.FCStd`:

[freecad_external_geo_weirdness.tar.gz](https://github.com/realthunder/FreeCAD/files/8713213/freecad_external_geo_weirdness.tar.gz)

This is sortof similar to [another issue](https://github.com/realthunder/FreeCAD_assembly3/issues/862) I submitted in the other repo which was resolved.  Except that one was for exported sketches and this is a binder who's parent contains no exported sketches.

```
OS: Arch Linux (i3/i3)
Word size of FreeCAD: 64-bit
Version: 2022.430.26244 +4758 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: b024b876480a533018fdc702145e9e38f8c54ba6
Python version: 3.9.12
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)
```

Thanks in advance!

**Comment by realthunder** [comment] 2022-05-18 04:43
This is a duplicate of #391 and has been fixed. I've got some problem building AppImage at the moment. I'll try to fix it soom. Meanwhile, please try [snap](https://snapcraft.io/freecad-realthunder) build if you can.

**Closed as completed** 2022-05-18 04:43 UTC
